/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    //id("buildlogic.java-library-conventions")
    java
}

repositories {
    mavenCentral()
}


dependencies {
    // Lucene Core
    implementation("org.apache.lucene:lucene-core:10.2.2")


    // Test framework
    testImplementation("org.apache.lucene:lucene-test-framework:10.2.0")
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}